feat: displays added events - admin user
CHUPITO-Org/FE-Chupito pull request #19
Opened 2023-07-27 18:13 UTC by vivianamck

## Conference App - Frontend

## Issue ticket number and link
https://trello.com/c/sITZm1Uf

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

## Pull request type

Please check the type of change your PR introduces:

- [X] :sparkles: Feature
- [ ] :bug: Bugfix
- [ ] :pencil2: Fixing typos
- [ ] :lipstick: :art: Code style update (formatting, renaming)
- [ ] :recycle: Refactoring (no functional changes, no api changes)
- [ ] :zap: Performance
- [ ] :pencil: Documentation content changes
- [ ] :white_check_mark: Unit testing
- [ ] :ok_hand: Updating due to code review suggest
- [ ] :rocket: Release: v
- [ ] :wrench: Add or update configuration files
- [ ] :hammer: Add or update development scripts
- [ ] :bricks: Infrastructure related changes

## What is the current module?

-  Displays events on cards - all users

## What is the new behavior?

- Added page displaying created events
- Added component for table with fields: Name, Date, Number of subscriptions, Status, Actions, filters for the table and button to create event.
- Added component for private route
- Created unit tests for table and component rendering
- Modified auth provider and auth reducer to get value from 'isadmin'

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

![image](https://github.com/CHUPITO-Org/FE-Chupito/assets/129223258/b71d95d9-1cdf-4453-a119-32ee727cb7b0)
![image](https://github.com/CHUPITO-Org/FE-Chupito/assets/129223258/58e2af70-c57b-49ac-afa2-4de388d19e2f)

2023-07-27 18:15 UTC, jlora-mck commented on src/components/AppRoutes/ProtectedRoute/ProtectedRoutes.tsx
> +    }
This looks cleaner! 
```suggestion
    if (!user) return null:
    return <Component />
```

2023-07-27 18:16 UTC, jlora-mck commented on src/components/EventsAdminView/EventAdminView.spec.tsx
> +})
Please remove

2023-07-27 18:16 UTC, jlora-mck commented on src/components/EventsAdminView/EventAdminView.spec.tsx
> +  render(<EventAdminView  {...props}/>)
if you dont want to use brackets lets go for this notation, the other is a bit misleading
```suggestion
const renderComponent = (props: EventsAdminViewProps) => render(<EventAdminView  {...props}/>)
```

2023-07-27 18:23 UTC, jlora-mck commented on src/components/EventsAdminView/EventAdminView.tsx
> +          : JSON.parse(JSON.stringify(events)).sort(sortAscending)
Why do we need to JSON.parse and JSON.stringify here ? are we not receiving this as an object from the back? Also lets not repeat code

2023-07-27 18:24 UTC, jlora-mck commented on src/components/EventsAdminView/EventAdminView.tsx
> +  selectedHeadquarter = '-1',
why not null ?

2023-07-27 18:25 UTC, jlora-mck commented on src/components/EventsAdminView/EventAdminView.tsx
> +          element.headquarter && element.headquarter.id === selectedHeadquarter
```suggestion
        ({ headquarter,  headquarter }: Conference) =>
          headquarter && headquarter.id === selectedHeadquarter
```

2023-07-27 18:26 UTC, jlora-mck commented on src/components/EventsAdminView/EventAdminView.tsx
> +                      sx={{ '&:last-child td, &:last-child th': { border: 0 } }}
Add this to a style

2023-07-27 18:26 UTC, jlora-mck commented on src/contexts/Auth/AuthProvider.tsx
> +  let initialState = { isAuth: false, userUid: '', email: '', username: '', isadmin: false }
```suggestion
  let initialState = { isAuth: false, userUid: '', email: '', username: '', isAdmin: false }
```

2023-07-27 18:27 UTC, jlora-mck commented on src/contexts/Auth/AuthProvider.tsx
>        const userResponse = await usersApi.getUserById(userUid)
```suggestion
      const { firstName, isAdmin } = await usersApi.getUserById(userUid)
```

2023-07-27 18:27 UTC, jlora-mck commented on src/contexts/Auth/AuthProvider.tsx
> +          isadmin: userResponse.isAdmin as boolean,
```suggestion
          username: firstName as string,
          isAdmin,
```

2023-07-27 18:28 UTC, jlora-mck commented on src/pages/EventsAdmin/EventsAdmin.tsx
> +      })
Please use async/await like the rest of the app

2023-07-27 18:29 UTC, jlora-mck requested changes
Great work! i added some comments... please there files that needs an enter at the end (the ones that have a red circle at the end of the file), Also didnt see eventsAdmin spec, did we forget it ? @vivianamck

2023-07-28 14:57 UTC, vivianamck commented on src/components/AppRoutes/ProtectedRoute/ProtectedRoutes.tsx
> +    }
Done

2023-07-28 14:58 UTC, vivianamck commented on src/components/EventsAdminView/EventAdminView.tsx
> +  selectedHeadquarter = '-1',
Done

2023-07-28 15:01 UTC, vivianamck commented on src/contexts/Auth/AuthProvider.tsx
> +  let initialState = { isAuth: false, userUid: '', email: '', username: '', isadmin: false }
Done

2023-07-28 15:03 UTC, vivianamck commented on src/contexts/Auth/AuthProvider.tsx
> +          isadmin: userResponse.isAdmin as boolean,
Done

2023-07-28 15:10 UTC, vivianamck commented on src/pages/EventsAdmin/EventsAdmin.tsx
Done

2023-07-28 15:17 UTC, vivianamck commented on src/components/EventsAdminView/EventAdminView.tsx
> +                      sx={{ '&:last-child td, &:last-child th': { border: 0 } }}
Done

2023-07-28 15:17 UTC, vivianamck commented on src/contexts/Auth/AuthProvider.tsx
>        const userResponse = await usersApi.getUserById(userUid)
Done

2023-07-28 15:18 UTC, vivianamck commented on src/pages/EventsAdmin/EventsAdmin.tsx
> +      })
Done

2023-07-28 15:43 UTC, jlora-mck approved these changes
Nice Work! We can improve the test but we can do it in a separated ticket

2023-07-28 15:45 UTC, FelipeLosada1996 approved these changes

2023-07-28 15:46 UTC, Sofiag8 approved these changes

2023-07-28 15:56 UTC, merged