feat: added event edit - admin user
CHUPITO-Org/FE-Chupito pull request #22
Opened 2023-08-04 15:05 UTC by vivianamck

## Conference App - Frontend

## Issue ticket number and link

https://trello.com/c/xK7uIL99

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

## Pull request type

Please check the type of change your PR introduces:

- [X] :sparkles: Feature
- [ ] :bug: Bugfix
- [ ] :pencil2: Fixing typos
- [ ] :lipstick: :art: Code style update (formatting, renaming)
- [ ] :recycle: Refactoring (no functional changes, no api changes)
- [ ] :zap: Performance
- [ ] :pencil: Documentation content changes
- [ ] :white_check_mark: Unit testing
- [ ] :ok_hand: Updating due to code review suggest
- [ ] :rocket: Release: v
- [ ] :wrench: Add or update configuration files
- [ ] :hammer: Add or update development scripts
- [ ] :bricks: Infrastructure related changes

## What is the current module?

- Button edit non-functional event

## What is the new behavior?

- Added functionality event edit by id
- Added event edit route
- Created components event edit
- Created test event edit
- Created autocomplete event edit form

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

2023-08-04 15:14 UTC, jlora-mck commented on src/api/events.js
> +  update =  (id, event) => (this.put(`${this.methodAll}/${id}`, event))
I think we dont need the parenthesis
```suggestion
  update =  (id, event) => this.put(`${this.methodAll}/${id}`, event)
```

2023-08-04 15:16 UTC, jlora-mck commented on src/components/EventEditView/EventEditView.spec.tsx
> +    fireEvent.click(getByRole('cancel'));
is this button a cancel that redirects ?

2023-08-04 15:16 UTC, jlora-mck commented on src/components/EventEditView/EventEditView.spec.tsx
> +  })
what is this for ?

2023-08-04 15:16 UTC, jlora-mck commented on src/components/EventEditView/EventEditView.tsx
> +}
Place all interfaces in a folder please

2023-08-04 15:18 UTC, jlora-mck commented on src/components/EventEditView/EventEditView.tsx
> +  const { id } = useParams<string>()
this block should be the first one of the component, note that if you have a correct lint configuration it will tell you that you are using code that hasnt been defined yet

2023-08-04 15:18 UTC, vivianamck commented on src/components/EventEditView/EventEditView.spec.tsx
> +    fireEvent.click(getByRole('cancel'));
Yes, redirects to events list

2023-08-04 15:18 UTC, jlora-mck commented on src/components/EventEditView/EventEditView.tsx
> +  const { id } = useParams<string>()
Also, why dont we create an object for this ? why have all these states if we can create an object in the state

2023-08-04 15:22 UTC, jlora-mck commented on src/components/EventEditView/EventEditView.tsx
> +      if (data.status == 200) handleCancelButton()
3 things here.. 

1. Always equals check with type

```suggestion
      if (data.status === 200) handleCancelButton()
```

2. why we need to ask if its 200, if we called the update here and didnt throw an error it should call that function
3. handleCancelButton doesnt look like a good name for something that its being by non canceling code, like here you made an update everything went fine and then you call a cancel method, please change the name to be more generic, something like `redirect`

2023-08-04 15:26 UTC, jlora-mck commented on src/components/EventEditView/EventEditView.tsx
> +            errorMessage=""
please remove if not using

2023-08-04 15:26 UTC, jlora-mck commented on src/components/EventsAdminView/EventAdminView.tsx
>        if (data.status == 200) {
while you here please change this to be ===

2023-08-04 15:27 UTC, jlora-mck requested changes
Please review the comments

2023-08-04 16:08 UTC, vivianamck commented on src/api/events.js
> +  update =  (id, event) => (this.put(`${this.methodAll}/${id}`, event))
Done

2023-08-04 17:37 UTC, vivianamck commented on src/components/EventEditView/EventEditView.spec.tsx
> +    fireEvent.click(getByRole('cancel'));
Changed text to redirect

2023-08-04 17:37 UTC, vivianamck commented on src/components/EventEditView/EventEditView.tsx
> +}
Done

2023-08-04 19:44 UTC, vivianamck commented on src/components/EventEditView/EventEditView.tsx
> +      if (data.status == 200) handleCancelButton()
Done

2023-08-04 20:26 UTC, vivianamck commented on src/components/EventsAdminView/EventAdminView.tsx
>        if (data.status == 200) {
Done

2023-08-09 13:04 UTC, vivianamck commented on src/components/EventEditView/EventEditView.tsx
> +  const { id } = useParams<string>()
Done

2023-08-09 13:34 UTC, jlora-mck commented on src/components/EventEditView/EventEditView.tsx
> +      const response = await api.getById(eventId)
destructuring please
```suggestion
      const {  name, ...others } = await api.getById(eventId)
```

2023-08-09 13:34 UTC, jlora-mck commented on src/components/EventEditView/EventEditView.tsx
> +        getType: response.type
do not repeat yourself

2023-08-09 13:35 UTC, jlora-mck commented on src/components/EventEditView/EventEditView.tsx
> +        getName: response.name,
this name looks like a method and is just a property, please rename all these, something like
getName rename to name

2023-08-09 13:35 UTC, jlora-mck commented on src/components/EventEditView/EventEditView.tsx
> +          "phoneNumber": getData.getphone
do not repeat yourself

2023-08-09 13:37 UTC, jlora-mck commented on src/components/EventTypes/EventTypes.tsx
> +  })
1. Please configure a linter
2. Never but never have a useEffect without dependecy array, its a bad pattern, please add dependecies
3. Please investigate why using useEffect without dependecy array is a bad pattern

2023-08-09 15:03 UTC, vivianamck commented on src/components/EventEditView/EventEditView.tsx
> +      const response = await api.getById(eventId)
Done

2023-08-09 15:04 UTC, vivianamck commented on src/components/EventEditView/EventEditView.tsx
> +        getType: response.type
Done

2023-08-09 15:04 UTC, vivianamck commented on src/components/EventEditView/EventEditView.tsx
> +          "phoneNumber": getData.getphone
Done

2023-08-09 17:19 UTC, vivianamck commented on src/components/EventTypes/EventTypes.tsx
> +  })
Done

2023-08-09 19:57 UTC, jlora-mck approved these changes

2023-08-09 19:59 UTC, FelipeLosada1996 approved these changes

2023-08-09 23:12 UTC, jose-sal-y-rosas requested changes
Please review feedback

2023-08-09 23:19 UTC, vivianamck commented on .gitignore
> +package-lock.json
Done

2023-08-09 23:23 UTC, jose-sal-y-rosas approved these changes
👍🏼

2023-08-09 23:27 UTC, merged