Viviana/feat/user login redirect
CHUPITO-Org/FE-Chupito pull request #23
Opened 2023-08-14 16:51 UTC by vivianamck

## Conference App - Frontend

## Issue ticket number and link

https://trello.com/c/C4DqafFX

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

## Pull request type

Please check the type of change your PR introduces:

- [X] :sparkles: Feature
- [ ] :bug: Bugfix
- [ ] :pencil2: Fixing typos
- [ ] :lipstick: :art: Code style update (formatting, renaming)
- [ ] :recycle: Refactoring (no functional changes, no api changes)
- [ ] :zap: Performance
- [ ] :pencil: Documentation content changes
- [ ] :white_check_mark: Unit testing
- [ ] :ok_hand: Updating due to code review suggest
- [ ] :rocket: Release: v
- [ ] :wrench: Add or update configuration files
- [ ] :hammer: Add or update development scripts
- [ ] :bricks: Infrastructure related changes

## What is the current module?

- Login redirect to events cards

## What is the new behavior?

- Added login redirect by user profile
- Admin redirect to events list view(create, edit and remove) and others redirect to events cards view

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

2023-08-14 17:08 UTC, jlora-mck commented on src/components/Login/Login.tsx
> +      : `/login`
Please refactor this in a way that is understandable, nested ternary are hard to ready and hard to mantain

2023-08-14 18:47 UTC, vivianamck commented on src/components/Login/Login.tsx
> +      : `/login`
Done

2023-08-15 13:55 UTC, jose-sal-y-rosas requested changes
Please review comment

2023-08-15 15:22 UTC, vivianamck commented on src/components/Login/Login.tsx
> +    let shouldRedirectTo = '/login'
Done

2023-08-16 14:29 UTC, FelipeLosada1996 approved these changes

2023-08-16 14:40 UTC, jose-sal-y-rosas approved these changes
👍🏼

2023-08-16 14:50 UTC, Sofiag8 approved these changes

2023-08-16 14:54 UTC, merged