feat: added responsive for events more info and events admin
CHUPITO-Org/FE-Chupito pull request #28
Opened 2023-08-24 13:05 UTC by vivianamck

## Conference App - Frontend

## Issue ticket number and link

https://trello.com/c/oB9exZjV

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

## Pull request type

Please check the type of change your PR introduces:

- [x] :sparkles: Feature
- [ ] :bug: Bugfix
- [ ] :pencil2: Fixing typos
- [ ] :lipstick: :art: Code style update (formatting, renaming)
- [ ] :recycle: Refactoring (no functional changes, no api changes)
- [ ] :zap: Performance
- [ ] :pencil: Documentation content changes
- [ ] :white_check_mark: Unit testing
- [ ] :ok_hand: Updating due to code review suggest
- [ ] :rocket: Release: v
- [ ] :wrench: Add or update configuration files
- [ ] :hammer: Add or update development scripts
- [ ] :bricks: Infrastructure related changes

## What is the current module?

- Cards and filters had responsive but its content was cut

## What is the new behavior?

- Responsive web design for views: cards events, more info and filter of events admin

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Responsive

- Before
  
<img width="253" alt="image" src="https://github.com/CHUPITO-Org/FE-Chupito/assets/129223258/7ed57824-da62-4c07-8fd2-c534206feccd">

<img width="280" alt="image" src="https://github.com/CHUPITO-Org/FE-Chupito/assets/129223258/3776bb34-bbfd-4280-8651-259f2dce654e">

![image](https://github.com/CHUPITO-Org/FE-Chupito/assets/129223258/cd5e6b21-e295-4e1d-a39a-8724d788e275)

- After
<img width="319" alt="image" src="https://github.com/CHUPITO-Org/FE-Chupito/assets/129223258/e02d5f7f-9077-411a-b01b-66f1702f158d">

<img width="356" alt="image" src="https://github.com/CHUPITO-Org/FE-Chupito/assets/129223258/b74de09a-b2e7-46b1-b316-f2fbc0c69561">

<img width="325" alt="image" src="https://github.com/CHUPITO-Org/FE-Chupito/assets/129223258/3de78be1-4544-45a2-8687-3bac75b9bd75">

2023-08-24 17:16 UTC, jose-sal-y-rosas requested changes
Please review comments

2023-08-24 17:16 UTC, jose-sal-y-rosas commented on src/pages/EventInfo/EventInfo.tsx
> +import { eventInfoStyles } from '../../shared/styles/EventInfo'
Please, could you describe why this is a shared style?

2023-08-24 20:25 UTC, jose-sal-y-rosas approved these changes
👍🏼

2023-08-25 15:11 UTC, FelipeLosada1996 approved these changes

2023-08-25 15:17 UTC, merged