Refactor EventInfo
CHUPITO-Org/FE-Chupito pull request #57
Opened 2024-01-19 15:05 UTC by milca19

## Conference App - Frontend

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

## Pull request type

Please check the type of change your PR introduces:

- [x] :sparkles: Feature
- [ ] :bug: Bugfix
- [ ] :pencil2: Fixing typos
- [ ] :lipstick: :art: Code style update (formatting, renaming)
- [ ] :recycle: Refactoring (no functional changes, no api changes)
- [ ] :zap: Performance
- [ ] :pencil: Documentation content changes
- [ ] :white_check_mark: Unit testing
- [ ] :ok_hand: Updating due to code review suggest
- [ ] :rocket: Release: v
- [ ] :wrench: Add or update configuration files
- [ ] :hammer: Add or update development scripts
- [ ] :bricks: Infrastructure related changes

## What is the current module?

-

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2024-01-19 15:56 UTC, jlora-mck commented on src/components/EventDetails/EventDetails.tsx
> +                        {eventDetails?.name}
DRY, dont repeat yourself
Please destructure eventDetails so you can use the properties without repeating the eventDetails prop

const { name } = eventDetails;
```suggestion
                        {name}
```

2024-01-19 15:57 UTC, jlora-mck commented on src/components/EventDetails/EventDetails.tsx
> +  }
This is not aligned to export, please install a linter to help you with this kind of code styling concerns

2024-01-19 16:10 UTC, jlora-mck commented on src/pages/EventInfo/EventInfo.tsx
> +const EventInfoPage = () => {
Why did we lose the type ?

2024-01-19 19:59 UTC, jose-sal-y-rosas requested changes
Please review comments

2024-01-19 19:59 UTC, jose-sal-y-rosas commented on .env.example
> -REACT_APP_BASE_PATH=http://localhost:5002/v1/
Please, could you describe the reason for removing this file? or lines?

2024-01-19 19:59 UTC, jose-sal-y-rosas commented on src/components/EventDetails/EventDetails.spec.tsx
> +    it('should render all elements', () => {
Please review all files: 2 spaces for tabs.

2024-01-19 19:59 UTC, jose-sal-y-rosas commented on src/contexts/UserContext.js
> +export const imageItems = [
Please, explain why are these images part of a context?

2024-01-22 14:01 UTC, jlora-mck commented on src/tools/index.js
> +]
Add a space at the end please

2024-01-22 17:19 UTC, jlora-mck commented on src/components/EventDetails/EventDetails.tsx
> +          {imageItems.map((item) => (
```suggestion
          {imageItems.map(({img, title}) => (
```

2024-01-22 17:20 UTC, jlora-mck commented on src/components/EventDetails/EventDetails.tsx
> +            <ImageListItem key={item.img}>
Lets change this, instead of img lets use title, this will help react a lot with the reconciliation

2024-01-22 17:23 UTC, jose-sal-y-rosas commented on .env.example
>  REACT_APP_STORAGE_BUCKET=
Please not consider this files as part of all changes

2024-01-22 17:27 UTC, jose-sal-y-rosas commented on src/contexts/UserContext.js
> +export const UserContext = React.createContext();
Please not consider this files as part of all changes

2024-01-22 20:41 UTC, jlora-mck commented on .env.example
> +REACT_APP_MEASUREMENT_ID=
You need to add a space at end here thats why you are seeing this file part of the changes

2024-01-22 20:57 UTC, jlora-mck approved these changes

2024-01-22 22:30 UTC, jose-sal-y-rosas requested changes
Please review feedback

2024-01-22 22:30 UTC, jose-sal-y-rosas commented on src/tools/index.js
> +export const imageItems = [
Please could you add a TODO comment why if this file is not moved within shared folder.

2024-01-22 23:02 UTC, jose-sal-y-rosas approved these changes
👍🏼

2024-01-22 23:04 UTC, merged